### ISSUE TITLE
quarks-utils import points to orphaned commit

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/quarks-secret#12]
I'm a little bit confused by the tagging in use (I'm going to guess `v1.0.x` are releases, and `v0.0.x` are development tags?), so I'm hoping that `v1.0.686` is a reasonable thing to import.

In `go.mod`, `quarks-utils` is being [imported](https://github.com/cloudfoundry-incubator/quarks-secret/blob/v1.0.686/go.mod#L6) at version v0.0.0-20200630135315-[de0c944c2813](https://github.com/cloudfoundry-incubator/quarks-utils/commit/de0c944c2813).  However, that commit appears to not be in any branch or tag; this means that it's impossible to pull it, so trying to import `quarks-secret` in turn fails.

Workaround: import `quarks-secret` at `v0.0.0-20200527034647-269daeb7e9ca` instead — that's essentially the commit before the `go.mod` change that pulled in the bad version.

Please let me know if I'm doing something dumb — I can reproduce this by
1. Check out `quarks-secret` (currently at 9f4080ec88a8929e74462383c0752ebe9b4e5da6)
2. Run `go mod tidy` on the fresh checkout.

**Comment by rohitsakala** [comment]
I am not able to reproduce this. New PR's will fix this.
