### ISSUE TITLE
Certificate rotation doesn't work

### ISSUE THREAD

**Issue by rohitsakala** [cloudfoundry-incubator/quarks-secret#19]
How to Reproduce ?

create ./docs/examples/certifcate.yaml
create ./docs/examples/rotate.yaml

Should have seen a different secret. But, the secret is unchanged. Waited for the meltdown period too.

**Comment by manno** [comment]
Judging from the integration tests only 'password'-type secrets are supported.

Added https://www.pivotaltracker.com/story/show/173920919

**Comment by manno** [comment]
https://github.com/cloudfoundry-incubator/quarks-secret/pull/27
