### ISSUE TITLE
possibility of incorrect secret loaded by applications

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/quarks-secret#3]
> The QuarksSecret controller can create copies of a generated secret across multiple namespaces, as long as the target secrets (that live in a namespace other than the namespace of the QuarksSecret) already exist, and have an annotation of:

based on above description it seems that empty secret is required in destination namespace. since secret will be present but empty, there is non-0 chance that application that loads such secret will in best case scenario fail or in worst case scenario load incorrect value. even in the best case scenario this potentially introduces pod restart behaviour that slows things down.

i would recommend switching to a different design to avoid this kind of problem. an alternative ive previously implemented is  described here https://github.com/k14s/secretgen-controller/blob/develop/docs/secret-export.md where no destination invalid secret exists at any point in time.

**Comment by manno** [comment]
@cppforlife thanks!

ping @viovanov

**Comment by manno** [comment]
We added a story to address this: https://www.pivotaltracker.com/story/show/173656732

**Comment by mudler** [comment]
This commit https://github.com/cloudfoundry-incubator/quarks-secret/commit/948be14571330dd024c9453b2a7fd948d8230822 should address the issue which is now documented here, thank you!
